import { describe, expect, it } from "vitest";

import {
  AI_MAX_FINDINGS,
  AI_MAX_HISTORY_TEXT_LENGTH,
  AI_MAX_MESSAGE_TEXT_LENGTH,
  AI_MAX_MESSAGES,
  AI_MAX_SAMPLE_ROWS_PER_TABLE,
  AI_MAX_SAMPLE_ROWS_PER_TURN,
  AI_MAX_SCHEMA_PROMPT_LENGTH,
  AI_MAX_USER_MESSAGE_LENGTH,
  EMAIL_MAX_LENGTH,
  MAX_REQUEST_BODY_BYTES,
  MAX_SCHEMAS_PER_USER,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  SCHEMA_LIST_DEFAULT_LIMIT,
  SCHEMA_LIST_MAX_LIMIT,
} from "./limits.js";

describe("limits", () => {
  it("keeps the limits agreed in the spec", () => {
    expect({
      EMAIL_MAX_LENGTH,
      PASSWORD_MIN_LENGTH,
      PASSWORD_MAX_LENGTH,
      MAX_REQUEST_BODY_BYTES,
      SCHEMA_LIST_DEFAULT_LIMIT,
      SCHEMA_LIST_MAX_LIMIT,
      MAX_SCHEMAS_PER_USER,
    }).toStrictEqual({
      EMAIL_MAX_LENGTH: 254,
      PASSWORD_MIN_LENGTH: 8,
      PASSWORD_MAX_LENGTH: 128,
      MAX_REQUEST_BODY_BYTES: 2_097_152,
      SCHEMA_LIST_DEFAULT_LIMIT: 50,
      SCHEMA_LIST_MAX_LIMIT: 100,
      MAX_SCHEMAS_PER_USER: 100,
    });
  });

  it.each([
    ["AI_MAX_USER_MESSAGE_LENGTH", AI_MAX_USER_MESSAGE_LENGTH, 4000],
    ["AI_MAX_MESSAGE_TEXT_LENGTH", AI_MAX_MESSAGE_TEXT_LENGTH, 8000],
    ["AI_MAX_MESSAGES", AI_MAX_MESSAGES, 40],
    ["AI_MAX_HISTORY_TEXT_LENGTH", AI_MAX_HISTORY_TEXT_LENGTH, 60_000],
    ["AI_MAX_SCHEMA_PROMPT_LENGTH", AI_MAX_SCHEMA_PROMPT_LENGTH, 80_000],
    ["AI_MAX_SAMPLE_ROWS_PER_TABLE", AI_MAX_SAMPLE_ROWS_PER_TABLE, 20],
    ["AI_MAX_SAMPLE_ROWS_PER_TURN", AI_MAX_SAMPLE_ROWS_PER_TURN, 200],
    ["AI_MAX_FINDINGS", AI_MAX_FINDINGS, 30],
  ])(
    "defines the AI limits of spec section 5: %s",
    (_name, value, expected) => {
      expect(value).toBe(expected);
    },
  );
});
