// The order follows the code table of the import / export plan (Task 2).
export const IMPORT_DIAGNOSTIC_CODES = [
  "source-too-large",
  "too-many-elements",
  "parse-failed",
  "syntax-error",
  "reference-not-found",
  "table-renamed",
  "enum-renamed",
  "index-renamed",
  "subject-area-renamed",
  "data-statements-ignored",
  "view-not-supported",
  "routine-not-supported",
  "trigger-not-supported",
  "sequence-not-supported",
  "statement-not-supported",
  "namespace-dropped",
  "index-expression-not-supported",
  "index-type-dropped",
  "check-converted-to-enum",
  "check-constraint-not-supported",
  "computed-column-not-supported",
  "type-approximated",
  "type-parameter-dropped",
  "identity-options-dropped",
  "type-not-supported",
  "default-approximated",
  "sequence-default-as-auto-increment",
  "default-not-supported",
  "on-update-not-supported",
  "provider-not-supported",
  "composite-type-not-supported",
  "scalar-list-as-custom",
  "index-option-dropped",
  "updated-at-not-supported",
  "comment-dropped",
  "color-dropped",
  "back-relation-missing",
  "implicit-many-to-many-not-supported",
  "many-to-many-not-supported",
] as const;

export type ImportDiagnosticCode = (typeof IMPORT_DIAGNOSTIC_CODES)[number];
