import { describe, expect, it } from "vitest";

import type { SqlDialect } from "../../generators/shared/generator-types.js";
import { unwrapOk } from "../../testing/unwrap-result.js";
import { classifyStatement, type StatementKind } from "./classify-statement.js";
import { scanSqlStatements } from "./statement-scanner.js";

function classify(
  source: string,
  dialect: SqlDialect,
): readonly StatementKind[] {
  return unwrapOk(scanSqlStatements(source, dialect)).map((statement) =>
    classifyStatement(statement, dialect),
  );
}

type Case = readonly [dialect: SqlDialect, source: string];

describe("classifyStatement", () => {
  it.each<Case>([
    ["postgresql", "CREATE TABLE public.t (id int)"],
    ["mysql", "CREATE TABLE `t` (`id` int)"],
    ["sqlserver", "CREATE TABLE [dbo].[t] ([id] int)"],
    ["postgresql", "CREATE UNIQUE INDEX i ON t (a)"],
    ["mysql", "CREATE INDEX i ON t (a)"],
    ["sqlserver", "CREATE UNIQUE NONCLUSTERED INDEX [i] ON [t] ([a])"],
    [
      "postgresql",
      "ALTER TABLE ONLY public.t ADD CONSTRAINT t_pkey PRIMARY KEY (id)",
    ],
    ["postgresql", "ALTER TABLE IF EXISTS t ADD CONSTRAINT u UNIQUE (a, b)"],
    ["mysql", "ALTER TABLE `t` ADD KEY `k` (`a`)"],
    [
      "sqlserver",
      "ALTER TABLE [dbo].[t] WITH CHECK ADD CONSTRAINT [fk] FOREIGN KEY([a]) REFERENCES [dbo].[u] ([id])",
    ],
    ["postgresql", "CREATE TYPE public.status AS ENUM ('a', 'b')"],
    ["postgresql", "COMMENT ON TABLE public.t IS 'x'"],
    ["postgresql", "COMMENT ON COLUMN public.t.a IS 'x'"],
  ])(
    "classifies a structure statement the parser reads in %s: %s",
    (dialect, source) => {
      expect(classify(source, dialect)).toStrictEqual(["parser"]);
    },
  );

  it.each<Case>([
    ["postgresql", "ALTER TABLE t ADD COLUMN c int"],
    ["postgresql", "ALTER TABLE t ADD c int"],
    ["postgresql", "ALTER TABLE t ADD COLUMN IF NOT EXISTS c int"],
    ["postgresql", 'ALTER TABLE IF EXISTS ONLY public.t ADD "c" int'],
    ["mysql", "ALTER TABLE `t` ADD COLUMN c int"],
    ["mysql", "ALTER TABLE `t` ADD c int"],
    ["mysql", "ALTER TABLE `t` ADD COLUMN IF NOT EXISTS c int"],
    ["mysql", "ALTER TABLE `t` ADD (`c` int, `d` int)"],
  ])(
    "classifies add column on postgresql and mysql as unsupported in %s: %s",
    (dialect, source) => {
      expect(classify(source, dialect)).toStrictEqual(["unsupported"]);
    },
  );

  it.each<Case>([
    ["sqlserver", "ALTER TABLE [dbo].[t] ADD [c] int NULL"],
    ["sqlserver", "ALTER TABLE [dbo].[t] ADD c int"],
  ])("keeps add column on sql server for the parser: %s", (dialect, source) => {
    expect(classify(source, dialect)).toStrictEqual(["parser"]);
  });

  it.each<Case>([
    ["mysql", "ALTER TABLE `t` ADD UNIQUE (c)"],
    ["mysql", "ALTER TABLE `t` ADD UNIQUE KEY k (c)"],
    ["mysql", "ALTER TABLE `t` ADD CONSTRAINT u UNIQUE (c)"],
    ["mysql", "ALTER TABLE `t` ADD CONSTRAINT UNIQUE (c)"],
  ])("classifies a mysql add unique as unsupported: %s", (dialect, source) => {
    expect(classify(source, dialect)).toStrictEqual(["unsupported"]);
  });

  it.each<Case>([
    ["postgresql", "ALTER TABLE ONLY public.t ADD CONSTRAINT u UNIQUE (c)"],
    ["postgresql", "ALTER TABLE t ADD UNIQUE (c)"],
  ])(
    "keeps add constraint unique on postgresql for the parser: %s",
    (dialect, source) => {
      expect(classify(source, dialect)).toStrictEqual(["parser"]);
    },
  );

  it.each<Case>([
    ["postgresql", "ALTER TABLE t ADD PRIMARY KEY (id)"],
    ["postgresql", "ALTER TABLE t ADD FOREIGN KEY (a) REFERENCES u (id)"],
    ["postgresql", "ALTER TABLE t ADD CHECK (a > 0)"],
    [
      "postgresql",
      "ALTER TABLE t ADD CONSTRAINT fk FOREIGN KEY (a) REFERENCES u (id)",
    ],
    ["mysql", "ALTER TABLE `t` ADD PRIMARY KEY (`id`)"],
    ["mysql", "ALTER TABLE `t` ADD FOREIGN KEY (a) REFERENCES u (id)"],
    ["mysql", "ALTER TABLE `t` ADD CHECK (a > 0)"],
    [
      "mysql",
      "ALTER TABLE `t` ADD CONSTRAINT `fk` FOREIGN KEY (a) REFERENCES u (id)",
    ],
    ["sqlserver", "ALTER TABLE [t] ADD PRIMARY KEY ([id])"],
    ["sqlserver", "ALTER TABLE [t] ADD CONSTRAINT [ck] CHECK ([a] > 0)"],
    ["sqlserver", "ALTER TABLE [t] ADD CONSTRAINT [pk] PRIMARY KEY ([id])"],
  ])(
    "keeps add primary key, foreign key and check for the parser in %s: %s",
    (dialect, source) => {
      expect(classify(source, dialect)).toStrictEqual(["parser"]);
    },
  );

  it.each<Case>([
    [
      "postgresql",
      "ALTER TABLE ONLY public.t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME t_id_seq)",
    ],
    [
      "postgresql",
      "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY",
    ],
    [
      "postgresql",
      "ALTER TABLE ONLY public.t ALTER COLUMN id SET DEFAULT nextval('t_id_seq'::regclass)",
    ],
    ["postgresql", `ALTER TABLE "t" ALTER "id" SET DEFAULT 1`],
  ])(
    "classifies a postgresql alter column the scanner reads: %s",
    (dialect, source) => {
      expect(classify(source, dialect)).toStrictEqual([
        "postgresqlAlterColumn",
      ]);
    },
  );

  it.each<Case>([
    [
      "sqlserver",
      "EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'x', @level0type=N'SCHEMA'",
    ],
    [
      "sqlserver",
      "EXECUTE [sys].[sp_addextendedproperty] N'MS_Description', N'x'",
    ],
    ["sqlserver", "exec sp_addextendedproperty 'MS_Description', 'x'"],
  ])("classifies a sql server extended property: %s", (dialect, source) => {
    expect(classify(source, dialect)).toStrictEqual([
      "sqlserverExtendedProperty",
    ]);
  });

  it.each<Case>([
    ["postgresql", "SET statement_timeout = 0"],
    ["postgresql", "SELECT pg_catalog.set_config('search_path', '', false)"],
    ["sqlserver", "USE [shop]"],
    ["sqlserver", "SET ANSI_NULLS ON"],
    ["postgresql", "BEGIN"],
    ["postgresql", "COMMIT"],
    ["mysql", "START TRANSACTION"],
    ["sqlserver", "DECLARE @a int"],
    ["mysql", "CREATE DATABASE shop"],
    ["postgresql", "CREATE SCHEMA app"],
    ["postgresql", "CREATE EXTENSION IF NOT EXISTS pgcrypto"],
    ["postgresql", "ALTER TABLE public.t OWNER TO postgres"],
    ["postgresql", "ALTER SEQUENCE public.t_id_seq OWNER TO postgres"],
    ["postgresql", "GRANT ALL ON TABLE t TO app"],
    ["postgresql", "REVOKE ALL ON SCHEMA public FROM PUBLIC"],
    ["mysql", "/*!40101 SET NAMES utf8mb4 */"],
    ["postgresql", "ROLLBACK"],
    ["sqlserver", "ALTER DATABASE [shop] SET COMPATIBILITY_LEVEL = 150"],
    ["mysql", "ALTER DATABASE shop SET x = 1"],
    ["sqlserver", "ALTER TABLE [dbo].[t] CHECK CONSTRAINT [fk]"],
    ["sqlserver", "ALTER TABLE [dbo].[t] WITH CHECK CHECK CONSTRAINT [fk]"],
    ["sqlserver", "ALTER TABLE [dbo].[t] NOCHECK CONSTRAINT [fk]"],
    ["sqlserver", "ALTER TABLE [dbo].[t] WITH NOCHECK NOCHECK CONSTRAINT ALL"],
  ])(
    "classifies a statement that describes no model structure as ignored in %s: %s",
    (dialect, source) => {
      expect(classify(source, dialect)).toStrictEqual(["ignored"]);
    },
  );

  it.each<Case>([
    ["postgresql", "DROP TABLE IF EXISTS public.t CASCADE"],
    ["mysql", "DROP TABLE IF EXISTS `t`"],
    ["sqlserver", "DROP VIEW [dbo].[v]"],
  ])("classifies drop statements as ignored in %s: %s", (dialect, source) => {
    expect(classify(source, dialect)).toStrictEqual(["ignored"]);
  });

  it.each<Case>([
    ["postgresql", "INSERT INTO t VALUES (1)"],
    ["postgresql", "COPY public.t (a) FROM stdin"],
    ["mysql", "UPDATE t SET a = 1"],
    ["sqlserver", "DELETE FROM t"],
    ["mysql", "LOCK TABLES `t` WRITE"],
    ["mysql", "UNLOCK TABLES"],
    ["mysql", "/*!40000 ALTER TABLE `t` DISABLE KEYS */"],
    ["mysql", "ALTER TABLE `t` ENABLE KEYS"],
  ])("classifies a data statement in %s: %s", (dialect, source) => {
    expect(classify(source, dialect)).toStrictEqual(["data"]);
  });

  it.each<readonly [SqlDialect, string, StatementKind]>([
    ["postgresql", "CREATE VIEW v AS SELECT 1", "view"],
    ["postgresql", "CREATE OR REPLACE MATERIALIZED VIEW v AS SELECT 1", "view"],
    ["sqlserver", "CREATE OR ALTER VIEW [v] AS SELECT 1", "view"],
    [
      "mysql",
      "/*!50001 CREATE ALGORITHM=UNDEFINED */ /*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */ /*!50001 VIEW `v` AS select 1 */",
      "view",
    ],
    [
      "postgresql",
      "CREATE OR REPLACE FUNCTION f() RETURNS int AS $$ SELECT 1; $$ LANGUAGE sql",
      "routine",
    ],
    ["sqlserver", "CREATE PROCEDURE [p] AS SELECT 1", "routine"],
    ["sqlserver", "CREATE PROC p AS SELECT 1", "routine"],
    [
      "postgresql",
      "CREATE TRIGGER trg BEFORE INSERT ON t FOR EACH ROW EXECUTE FUNCTION f()",
      "trigger",
    ],
    [
      "mysql",
      "CREATE DEFINER=`root`@`localhost` TRIGGER `trg` BEFORE INSERT ON `t` FOR EACH ROW SET @a = 1",
      "trigger",
    ],
    ["postgresql", "CREATE SEQUENCE public.s START WITH 1", "sequence"],
    ["postgresql", "ALTER SEQUENCE public.s OWNED BY public.t.id", "sequence"],
  ])(
    "classifies a model concept core lacks in %s: %s",
    (dialect, source, kind) => {
      expect(classify(source, dialect)).toStrictEqual([kind]);
    },
  );

  it.each<Case>([
    ["postgresql", "CREATE DOMAIN d AS int"],
    ["postgresql", "CREATE POLICY p ON t USING (true)"],
    ["postgresql", "CREATE RULE r AS ON INSERT TO t DO NOTHING"],
    ["postgresql", "CREATE STATISTICS s ON a, b FROM t"],
    ["postgresql", "CREATE TYPE public.pair AS (a int, b int)"],
    ["postgresql", "ALTER TABLE public.t ENABLE ROW LEVEL SECURITY"],
    ["postgresql", "COMMENT ON INDEX i IS 'x'"],
  ])(
    "classifies a structure core does not model as unsupported in %s: %s",
    (dialect, source) => {
      expect(classify(source, dialect)).toStrictEqual(["unsupported"]);
    },
  );

  it.each<Case>([
    ["postgresql", "VACUUM t"],
    ["postgresql", "SELECT 1"],
    ["postgresql", "(SELECT 1)"],
    ["postgresql", "CREATE PUBLICATION p FOR TABLE t"],
    ["postgresql", "ALTER TABLE t ALTER COLUMN a SET NOT NULL"],
    ["postgresql", "ALTER TABLE t DROP COLUMN a"],
    ["postgresql", "ALTER TABLE"],
    ["postgresql", "COMMENT ON"],
    ["postgresql", "LOCK TABLE t"],
    ["mysql", "ALTER TABLE t ALTER COLUMN a SET DEFAULT 1"],
    ["sqlserver", "EXEC dbo.do_something"],
    ["postgresql", "EXEC sp_addextendedproperty 'MS_Description', 'x'"],
    ["postgresql", "ALTER TABLE t NOCHECK CONSTRAINT c"],
    ["sqlserver", "ALTER DATABASE [shop] MODIFY FILE (NAME = f)"],
    ["postgresql", "CREATE UNLOGGED TABLE t (a int)"],
    ["postgresql", "CREATE TEMPORARY TABLE t (a int)"],
    ["mysql", "CREATE TEMP TABLE t (a int)"],
  ])(
    "classifies an unknown statement as unsupported in %s: %s",
    (dialect, source) => {
      expect(classify(source, dialect)).toStrictEqual(["unsupported"]);
    },
  );
});
