import { describe, expect, it } from "vitest";

import { unwrapOk } from "../../testing/unwrap-result.js";
import {
  readPostgresqlAlterColumn,
  type PostgresqlAlterColumn,
} from "./postgresql-identity.js";
import { scanSqlStatements } from "./statement-scanner.js";

function read(source: string): readonly (PostgresqlAlterColumn | null)[] {
  return unwrapOk(scanSqlStatements(source, "postgresql")).map(
    readPostgresqlAlterColumn,
  );
}

describe("readPostgresqlAlterColumn", () => {
  it("reads an identity added by pg_dump", () => {
    expect(
      read(
        "\nALTER TABLE public.t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;",
      ),
    ).toStrictEqual([
      {
        tableName: "t",
        columnName: "id",
        start: 1,
        change: { kind: "identity" },
      },
    ]);
  });

  it("reads an identity with sequence options", () => {
    expect(
      read(`ALTER TABLE ONLY "T" ALTER "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_id_seq
    START WITH 1
    INCREMENT BY 1
    CACHE 1
);`),
    ).toStrictEqual([
      {
        tableName: "T",
        columnName: "Id",
        start: 0,
        change: { kind: "identity" },
      },
    ]);
  });

  it.each([
    ["'it''s'", { kind: "string", text: "it''s" }],
    ["42", { kind: "number", text: "42" }],
    ["TRUE", { kind: "boolean", text: "TRUE" }],
    [
      "nextval('public.t_id_seq'::regclass)",
      { kind: "expression", text: "nextval('public.t_id_seq'::regclass)" },
    ],
    ["'a'::text", { kind: "expression", text: "'a'::text" }],
    ["- 5", { kind: "expression", text: "- 5" }],
    ["now ( )", { kind: "expression", text: "now ( )" }],
  ] as const)("reads a default set through alter column: %s", (text, raw) => {
    expect(
      read(`ALTER TABLE ONLY public.t ALTER COLUMN c SET DEFAULT ${text};`),
    ).toStrictEqual([
      {
        tableName: "t",
        columnName: "c",
        start: 0,
        change: { kind: "default", raw },
      },
    ]);
  });

  it("strips the schema of the table name", () => {
    expect(
      read(`ALTER TABLE ONLY "app"."orders" ALTER COLUMN id SET DEFAULT 1`).map(
        (change) => change?.tableName,
      ),
    ).toStrictEqual(["orders"]);
  });

  it.each([
    "ALTER TABLE t ALTER COLUMN c SET NOT NULL",
    "ALTER TABLE t ALTER COLUMN c DROP DEFAULT",
    "ALTER TABLE t ALTER COLUMN c SET DEFAULT",
    "ALTER TABLE t ALTER COLUMN c ADD GENERATED ALWAYS AS (a + 1) STORED",
    "ALTER TABLE t ALTER COLUMN c ADD GENERATED ALWAYS AS IDENTITY, ALTER COLUMN d SET NOT NULL",
    "ALTER TABLE t ADD COLUMN c int",
    "CREATE TABLE t (c int)",
  ])("returns null for another alter column form: %s", (source) => {
    expect(read(source)).toStrictEqual([null]);
  });
});
