import type { SqlStatement } from "./statement-scanner.js";
import {
  isNameAt,
  isSymbolAt,
  readParenthesizedList,
  readQualifiedName,
  wordAt,
  type Tokens,
  type TokenRange,
} from "./sql-token-reading.js";
import {
  readTableKey,
  readUniqueConstraint,
  type SqlTableKey,
  type SqlUniqueConstraint,
} from "./sql-table-keys.js";

export type SqlColumnDefinition = {
  // The `value` of the column name token (without quotes).
  readonly name: string;
  // The offset of the column name token.
  readonly start: number;
  // The source text of the type; "" when the column declares no type (a SQL
  // Server computed column).
  readonly rawType: string;
  // The offset of rawType; the end of the name when rawType is "".
  readonly typeStart: number;
  // The source text after DEFAULT up to the next constraint word, so a number
  // keeps every digit; null without DEFAULT.
  readonly defaultText: string | null;
  readonly hasOnUpdate: boolean;
  readonly hasCollation: boolean;
  readonly isComputed: boolean;
};

export type SqlTableDefinition = {
  // Without the schema.
  readonly tableName: string;
  // Whether the name has a schema (`s.t`).
  readonly isQualified: boolean;
  readonly start: number;
  readonly columns: readonly SqlColumnDefinition[];
  readonly uniqueConstraints: readonly SqlUniqueConstraint[];
  readonly keys: readonly SqlTableKey[];
};

/** Words that end the type of a column definition (CHARACTER only before SET). */
export const COLUMN_CONSTRAINT_WORDS: ReadonlySet<string> = new Set([
  "NOT",
  "NULL",
  "DEFAULT",
  "CONSTRAINT",
  "PRIMARY",
  "UNIQUE",
  "KEY",
  "REFERENCES",
  "CHECK",
  "COLLATE",
  "CHARSET",
  "CHARACTER",
  "GENERATED",
  "AS",
  "AUTO_INCREMENT",
  "COMMENT",
  "ON",
  "ROWGUIDCOL",
  "SPARSE",
  "VISIBLE",
  "INVISIBLE",
]);

// Words that start a table element other than a column.
const TABLE_CONSTRAINT_WORDS: ReadonlySet<string> = new Set([
  "CONSTRAINT",
  "PRIMARY",
  "UNIQUE",
  "FOREIGN",
  "CHECK",
  "KEY",
  "INDEX",
  "FULLTEXT",
  "SPATIAL",
  "EXCLUDE",
  "LIKE",
]);

// The first word of each referential action after `ON UPDATE`.
const FOREIGN_KEY_ACTION_WORDS: ReadonlySet<string> = new Set([
  "CASCADE",
  "RESTRICT",
  "SET",
  "NO",
]);

type ColumnAttributes = Pick<
  SqlColumnDefinition,
  "hasOnUpdate" | "hasCollation" | "isComputed"
>;

function isTypeEndAt(tokens: Tokens, index: number, depth: number): boolean {
  const word = wordAt(tokens, index);
  return (
    tokens[index]?.depth === depth &&
    word !== null &&
    COLUMN_CONSTRAINT_WORDS.has(word) &&
    (word !== "CHARACTER" || wordAt(tokens, index + 1) === "SET")
  );
}

// Reads the attributes after the type, at the depth of the column definition.
function readAttributes(
  tokens: Tokens,
  range: TokenRange,
  depth: number,
): ColumnAttributes {
  let isInReferences = false;
  let hasOnUpdate = false;
  let hasCollation = false;
  let isComputed = false;
  for (let index = range.start; index < range.end; index += 1) {
    const word = tokens[index]?.depth === depth ? wordAt(tokens, index) : null;
    const next = wordAt(tokens, index + 1);
    isInReferences ||= word === "REFERENCES";
    const isForeignKeyAction =
      isInReferences &&
      FOREIGN_KEY_ACTION_WORDS.has(wordAt(tokens, index + 2) ?? "");
    hasOnUpdate ||= word === "ON" && next === "UPDATE" && !isForeignKeyAction;
    hasCollation ||=
      word === "COLLATE" ||
      word === "CHARSET" ||
      (word === "CHARACTER" && next === "SET");
    isComputed ||= word === "AS" && isSymbolAt(tokens, index + 1, "(");
  }
  return { hasOnUpdate, hasCollation, isComputed };
}

function readDefaultText(
  tokens: Tokens,
  range: TokenRange,
  depth: number,
  source: string,
): string | null {
  let first = range.start;
  // `GENERATED BY DEFAULT AS IDENTITY` is not a default.
  while (
    first < range.end &&
    !(
      tokens[first]?.depth === depth &&
      wordAt(tokens, first) === "DEFAULT" &&
      wordAt(tokens, first - 1) !== "BY"
    )
  ) {
    first += 1;
  }
  first += 1;
  let end = first + 1;
  while (end < range.end && !isTypeEndAt(tokens, end, depth)) {
    end += 1;
  }
  const firstToken = tokens[first];
  const lastToken = tokens[end - 1];
  return first < range.end &&
    firstToken !== undefined &&
    lastToken !== undefined
    ? source.slice(firstToken.start, lastToken.start + lastToken.text.length)
    : null;
}

// The source text of the tokens in range; null for an empty range.
function readTypeText(
  tokens: Tokens,
  range: TokenRange,
  source: string,
): { readonly text: string; readonly start: number } | null {
  const first = tokens[range.start];
  const last = tokens[range.end - 1];
  return range.end > range.start && first !== undefined && last !== undefined
    ? {
        text: source.slice(first.start, last.start + last.text.length),
        start: first.start,
      }
    : null;
}

function readColumn(
  tokens: Tokens,
  range: TokenRange,
  source: string,
): SqlColumnDefinition | null {
  const name = tokens[range.start];
  if (name === undefined || !isNameAt(tokens, range.start)) {
    return null;
  }
  let typeEnd = range.start + 1;
  while (typeEnd < range.end && !isTypeEndAt(tokens, typeEnd, name.depth)) {
    typeEnd += 1;
  }
  const type = readTypeText(
    tokens,
    { start: range.start + 1, end: typeEnd },
    source,
  );
  const attributes = readAttributes(
    tokens,
    { start: typeEnd, end: range.end },
    name.depth,
  );
  return {
    name: name.value,
    start: name.start,
    rawType: type?.text ?? "",
    typeStart: type?.start ?? name.start + name.text.length,
    defaultText: readDefaultText(
      tokens,
      { start: typeEnd, end: range.end },
      name.depth,
      source,
    ),
    ...attributes,
    // SQL Server `c AS <expression> [PERSISTED]` declares no type.
    isComputed:
      attributes.isComputed || wordAt(tokens, range.start + 1) === "AS",
  };
}

/**
 * Reads the column definitions and table-level unique constraints of
 * `CREATE TABLE [IF NOT EXISTS] [schema.]t (…)` for what @dbml/core 10.2.0
 * drops; null for any other statement. `source` is the text the statement was
 * scanned from.
 */
export function readSqlTableDefinition(
  statement: SqlStatement,
  source: string,
): SqlTableDefinition | null {
  const { tokens } = statement;
  if (wordAt(tokens, 0) !== "CREATE" || wordAt(tokens, 1) !== "TABLE") {
    return null;
  }
  const hasIfNotExists =
    wordAt(tokens, 2) === "IF" &&
    wordAt(tokens, 3) === "NOT" &&
    wordAt(tokens, 4) === "EXISTS";
  const nameIndex = hasIfNotExists ? 5 : 2;
  const table = readQualifiedName(tokens, nameIndex);
  if (table === null || !isSymbolAt(tokens, table.next, "(")) {
    return null;
  }
  const list = readParenthesizedList(tokens, table.next);
  if (list.close === tokens.length) {
    return null;
  }
  const isColumn = (range: TokenRange): boolean =>
    !TABLE_CONSTRAINT_WORDS.has(wordAt(tokens, range.start) ?? "");
  const elements = list.items.filter((range) => !isColumn(range));
  return {
    tableName: table.lastName,
    isQualified: table.next > nameIndex + 1,
    start: statement.start,
    columns: list.items
      .filter(isColumn)
      .flatMap((range) => readColumn(tokens, range, source) ?? []),
    uniqueConstraints: elements.flatMap(
      (range) => readUniqueConstraint(tokens, range.start, range.end) ?? [],
    ),
    keys: elements.flatMap(
      (range) => readTableKey(tokens, range.start, range.end) ?? [],
    ),
  };
}
