export const enAiSampleData = {
  title: "Sample data",
  caption: "Sample rows for table {{table}}",
  format: "Format",
  formats: {
    postgresql: "PostgreSQL",
    mysql: "MySQL",
    sqlserver: "SQL Server",
    json: "JSON",
  },
  copy: "Copy",
  copied: "Copied to the clipboard",
  copyFailed: "Could not copy to the clipboard",
  download: "Download",
  outdated:
    "The schema changed after this data was generated. Generate it again.",
  retry: "Generate again",
  rowCount_one: "{{count}} row",
  rowCount_other: "{{count}} rows",
  sqlReminder:
    "This data was generated by AI. Read the SQL before you run it on a database.",
} as const;
