import type { SchemaDocument } from "../../../model/schema-document.js";
import {
  buildSchema,
  makeColumn,
  makeEnum,
  makeIndex,
  makeRelation,
  makeTable,
} from "../../../testing/factories.js";
import type { ImportDiagnostic } from "../../shared/import-types.js";

// Written in the shape `pg_dump --schema-only` of PostgreSQL 18 gives: the
// \restrict guard lines, session settings, a serial column through
// CREATE SEQUENCE and ALTER COLUMN … SET DEFAULT nextval, an identity added
// through ALTER TABLE, constraints added through ALTER TABLE ONLY, comments
// and owners after each object.

export const PG_DUMP_SOURCE = `--
-- PostgreSQL database dump
--

\\restrict Qd7GzBvTk3cXh8pWm1nLsA9eRfJ2yKoU4iVbN7tZ5qHgD0wSjPxCaE6lMrY

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: order_status; Type: TYPE; Schema: public; Owner: shop
--

CREATE TYPE public.order_status AS ENUM (
    'pending',
    'paid',
    'shipped'
);


ALTER TYPE public.order_status OWNER TO shop;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: customers; Type: TABLE; Schema: public; Owner: shop
--

CREATE TABLE public.customers (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    display_name text
);


ALTER TABLE public.customers OWNER TO shop;

--
-- Name: TABLE customers; Type: COMMENT; Schema: public; Owner: shop
--

COMMENT ON TABLE public.customers IS 'People who place orders';


--
-- Name: COLUMN customers.email; Type: COMMENT; Schema: public; Owner: shop
--

COMMENT ON COLUMN public.customers.email IS 'Login e-mail, it''s unique';


--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: shop
--

CREATE SEQUENCE public.customers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.customers_id_seq OWNER TO shop;

--
-- Name: customers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: shop
--

ALTER SEQUENCE public.customers_id_seq OWNED BY public.customers.id;


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: shop
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    line_no integer NOT NULL,
    quantity integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.order_items OWNER TO shop;

--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: shop
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: shop
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    customer_id integer NOT NULL,
    status public.order_status DEFAULT 'pending'::public.order_status NOT NULL,
    total numeric(12,2) DEFAULT 0.00 NOT NULL,
    placed_at timestamp with time zone DEFAULT now() NOT NULL,
    weight double precision
);


ALTER TABLE public.orders OWNER TO shop;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: shop
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers id; Type: DEFAULT; Schema: public; Owner: shop
--

ALTER TABLE ONLY public.customers ALTER COLUMN id SET DEFAULT nextval('public.customers_id_seq'::regclass);


--
-- Name: customers customers_email_key; Type: CONSTRAINT; Schema: public; Owner: shop
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_email_key UNIQUE (email);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: shop
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_order_id_line_no_key; Type: CONSTRAINT; Schema: public; Owner: shop
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_order_id_line_no_key UNIQUE (order_id, line_no);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: shop
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: shop
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: orders_customer_id_idx; Type: INDEX; Schema: public; Owner: shop
--

CREATE INDEX orders_customer_id_idx ON public.orders USING btree (customer_id);


--
-- Name: order_items order_items_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: shop
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- Name: orders orders_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: shop
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- PostgreSQL database dump complete
--

\\unrestrict Qd7GzBvTk3cXh8pWm1nLsA9eRfJ2yKoU4iVbN7tZ5qHgD0wSjPxCaE6lMrY

`;

const IMPORTED_NAME = "Imported";

export const PG_DUMP_EXPECTED: SchemaDocument = buildSchema({
  name: IMPORTED_NAME,
  enums: [
    makeEnum({
      id: "enum_status",
      name: "order_status",
      values: ["pending", "paid", "shipped"],
    }),
  ],
  tables: [
    makeTable({
      id: "tbl_customers",
      comment: "People who place orders",
      primaryKeyColumnIds: ["col_customers_id"],
    }),
    makeTable({
      id: "tbl_items",
      name: "order_items",
      primaryKeyColumnIds: ["col_items_id"],
    }),
    makeTable({ id: "tbl_orders", primaryKeyColumnIds: ["col_orders_id"] }),
  ],
  columns: [
    makeColumn({
      id: "col_customers_id",
      tableId: "tbl_customers",
      name: "id",
      isAutoIncrement: true,
    }),
    makeColumn({
      id: "col_customers_email",
      tableId: "tbl_customers",
      name: "email",
      type: { kind: "varchar", length: 255 },
      isUnique: true,
      comment: "Login e-mail, it's unique",
    }),
    makeColumn({
      id: "col_customers_name",
      tableId: "tbl_customers",
      name: "display_name",
      type: { kind: "text" },
      isNullable: true,
    }),
    makeColumn({
      id: "col_items_id",
      tableId: "tbl_items",
      name: "id",
      type: { kind: "bigint" },
      isAutoIncrement: true,
    }),
    makeColumn({
      id: "col_items_order",
      tableId: "tbl_items",
      name: "order_id",
      type: { kind: "bigint" },
    }),
    makeColumn({ id: "col_items_line", tableId: "tbl_items", name: "line_no" }),
    makeColumn({
      id: "col_items_quantity",
      tableId: "tbl_items",
      name: "quantity",
      defaultValue: { kind: "literal", value: "1" },
    }),
    makeColumn({
      id: "col_orders_id",
      tableId: "tbl_orders",
      name: "id",
      type: { kind: "bigint" },
      isAutoIncrement: true,
    }),
    makeColumn({
      id: "col_orders_customer",
      tableId: "tbl_orders",
      name: "customer_id",
    }),
    makeColumn({
      id: "col_orders_status",
      tableId: "tbl_orders",
      name: "status",
      type: { kind: "enum", enumId: "enum_status" },
      defaultValue: { kind: "literal", value: "pending" },
    }),
    makeColumn({
      id: "col_orders_total",
      tableId: "tbl_orders",
      name: "total",
      type: { kind: "decimal", precision: 12, scale: 2 },
      defaultValue: { kind: "literal", value: "0.00" },
    }),
    makeColumn({
      id: "col_orders_placed",
      tableId: "tbl_orders",
      name: "placed_at",
      type: { kind: "timestamptz" },
      defaultValue: { kind: "currentTimestamp" },
    }),
    makeColumn({
      id: "col_orders_weight",
      tableId: "tbl_orders",
      name: "weight",
      type: { kind: "double" },
      isNullable: true,
    }),
  ],
  indexes: [
    makeIndex({
      id: "idx_items_order_line",
      tableId: "tbl_items",
      name: "order_items_order_id_line_no_key",
      columnIds: ["col_items_order", "col_items_line"],
      isUnique: true,
    }),
    makeIndex({
      id: "idx_orders_customer",
      tableId: "tbl_orders",
      name: "orders_customer_id_idx",
      columnIds: ["col_orders_customer"],
    }),
  ],
  relations: [
    makeRelation({
      id: "rel_items_orders",
      fromTableId: "tbl_items",
      toTableId: "tbl_orders",
      columnPairs: [
        { fromColumnId: "col_items_order", toColumnId: "col_orders_id" },
      ],
      onDelete: "cascade",
    }),
    makeRelation({
      id: "rel_orders_customers",
      fromTableId: "tbl_orders",
      toTableId: "tbl_customers",
      columnPairs: [
        { fromColumnId: "col_orders_customer", toColumnId: "col_customers_id" },
      ],
    }),
  ],
});

// The \restrict and \unrestrict lines are psql meta-commands that are ignored
// without a diagnostic; the sequence statements and the nextval default of the
// serial column come from CREATE SEQUENCE … OWNED BY.
// Ids follow createImportTestOptions(): the enum, then tables, then columns.
export const PG_DUMP_EXPECTED_DIAGNOSTICS: readonly ImportDiagnostic[] = [
  {
    code: "sequence-not-supported",
    location: { line: 70, column: 1 },
    path: null,
  },
  {
    code: "sequence-not-supported",
    location: { line: 85, column: 1 },
    path: null,
  },
  {
    code: "sequence-default-as-auto-increment",
    location: { line: 150, column: 1 },
    path: ["columns", "col_5", "isAutoIncrement"],
  },
];
