CREATE TYPE "flag_status" AS ENUM ('active', 'inactive');

CREATE TABLE "all_types" (
  "id" integer NOT NULL,
  "smallint_value" smallint NOT NULL DEFAULT -32768,
  "integer_value" integer NOT NULL DEFAULT 42,
  "bigint_value" bigint NOT NULL DEFAULT 9223372036854775807,
  "decimal_value" numeric(12, 2) NOT NULL DEFAULT 1234567890.12,
  "real_value" real NOT NULL DEFAULT 1.5e10,
  "double_value" double precision NOT NULL DEFAULT -2.25,
  "boolean_value" boolean NOT NULL DEFAULT true,
  "char_value" char(3) NOT NULL DEFAULT 'abc',
  "varchar_value" varchar(20) NOT NULL DEFAULT 'it''s',
  "text_value" text NOT NULL DEFAULT 'a\b',
  "uuid_value" uuid NOT NULL DEFAULT '123e4567-e89b-12d3-a456-426614174000',
  "date_value" date NOT NULL DEFAULT '2026-01-02',
  "time_value" time NOT NULL DEFAULT '12:34:56.789',
  "timestamp_value" timestamp NOT NULL DEFAULT '2026-01-02T03:04:05',
  "timestamptz_value" timestamptz NOT NULL DEFAULT '2026-01-02T03:04:05.123+07:00',
  "timestamp_now" timestamp NOT NULL DEFAULT now(),
  "timestamptz_now" timestamptz NOT NULL DEFAULT now(),
  "json_value" jsonb NOT NULL DEFAULT '{"note":"it''s"}',
  "binary_value" bytea,
  "enum_value" "flag_status" NOT NULL DEFAULT 'active',
  CONSTRAINT "all_types_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "auto_integer" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONSTRAINT "auto_integer_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "auto_smallint" (
  "id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONSTRAINT "auto_smallint_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "auto_trailing" (
  "a" integer NOT NULL,
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONSTRAINT "auto_trailing_pkey" PRIMARY KEY ("a", "id")
);

CREATE TABLE "auto_wide_key" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code_a" varchar(700) NOT NULL,
  "code_b" varchar(700) NOT NULL,
  CONSTRAINT "auto_wide_key_pkey" PRIMARY KEY ("id", "code_a", "code_b")
);

CREATE TABLE "binary_keys" (
  "id" integer NOT NULL,
  "hash" bytea NOT NULL,
  CONSTRAINT "binary_keys_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "char_unique" (
  "id" integer NOT NULL,
  "code" char(300) NOT NULL,
  CONSTRAINT "char_unique_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "char_unique_code_key" UNIQUE ("code")
);

CREATE TABLE "custom_required" (
  "id" integer NOT NULL,
  "payload" tsvector NOT NULL,
  CONSTRAINT "custom_required_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "custom_values" (
  "id" integer NOT NULL,
  "shape" geometry(Point, 4326),
  "address" inet NOT NULL DEFAULT '127.0.0.1',
  CONSTRAINT "custom_values_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "cycle_a" (
  "id" integer NOT NULL,
  "b_id" integer,
  CONSTRAINT "cycle_a_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "cycle_b" (
  "id" integer NOT NULL,
  "a_id" integer,
  CONSTRAINT "cycle_b_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "default_children" (
  "id" integer NOT NULL,
  "parent_id" integer NOT NULL DEFAULT 0,
  CONSTRAINT "default_children_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "default_parents" (
  "id" integer NOT NULL,
  CONSTRAINT "default_parents_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "five_part_keys" (
  "id" integer NOT NULL,
  "q1" varchar(700) NOT NULL,
  "q2" varchar(700) NOT NULL,
  "q3" varchar(700) NOT NULL,
  "q4" varchar(700) NOT NULL,
  "q5" varchar(700) NOT NULL,
  CONSTRAINT "five_part_keys_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "five_part_refs" (
  "id" integer NOT NULL,
  "q1" varchar(700) NOT NULL,
  "q2" varchar(700) NOT NULL,
  "q3" varchar(700) NOT NULL,
  "q4" varchar(700) NOT NULL,
  "q5" varchar(700) NOT NULL,
  CONSTRAINT "five_part_refs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "fixed_keys" (
  "code" char(500) NOT NULL,
  CONSTRAINT "fixed_keys_pkey" PRIMARY KEY ("code")
);

CREATE TABLE "fixed_refs" (
  "id" integer NOT NULL,
  "fixed_code" char(500) NOT NULL,
  CONSTRAINT "fixed_refs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "fixed_unique" (
  "id" integer NOT NULL,
  "code" char(900) NOT NULL,
  CONSTRAINT "fixed_unique_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fixed_unique_code_key" UNIQUE ("code")
);

CREATE TABLE "flags" (
  "id" integer NOT NULL,
  "status" "flag_status",
  "is_primary" boolean NOT NULL,
  CONSTRAINT "flags_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "flags_is_primary_key" UNIQUE ("is_primary")
);

CREATE TABLE "four_part_keys" (
  "id" integer NOT NULL,
  "p1" varchar(192) NOT NULL,
  "p2" varchar(192) NOT NULL,
  "p3" varchar(192) NOT NULL,
  "p4" varchar(192) NOT NULL,
  CONSTRAINT "four_part_keys_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "fractional_times" (
  "id" integer NOT NULL,
  "starts_at" time NOT NULL DEFAULT '12:34:56.123456789',
  "created_at" timestamp NOT NULL DEFAULT '2026-01-02T03:04:05.12345678',
  CONSTRAINT "fractional_times_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "json_keys" (
  "doc" jsonb NOT NULL,
  CONSTRAINT "json_keys_pkey" PRIMARY KEY ("doc")
);

CREATE TABLE "json_refs" (
  "id" integer NOT NULL,
  "doc" jsonb NOT NULL,
  CONSTRAINT "json_refs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "json_unique" (
  "id" integer NOT NULL,
  "doc" jsonb NOT NULL,
  CONSTRAINT "json_unique_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "json_unique_doc_key" UNIQUE ("doc")
);

CREATE TABLE "leaf" (
  "id" integer NOT NULL,
  "left_id" integer NOT NULL,
  "right_id" integer NOT NULL,
  CONSTRAINT "leaf_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "left" (
  "id" integer NOT NULL,
  "root_id" integer NOT NULL,
  CONSTRAINT "left_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "long_comments" (
  "id" integer NOT NULL,
  "note" text NOT NULL,
  "surrogate_note" text NOT NULL,
  CONSTRAINT "long_comments_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "long_unique" (
  "id" integer NOT NULL,
  "code" varchar(1000) NOT NULL,
  CONSTRAINT "long_unique_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "long_unique_code_key" UNIQUE ("code")
);

CREATE TABLE "no_key_rows" (
  "note" text NOT NULL,
  "value" integer NOT NULL
);

CREATE TABLE "nullable_unique" (
  "id" integer NOT NULL,
  "code" varchar(20),
  "alt_code" varchar(20),
  CONSTRAINT "nullable_unique_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "nullable_unique_code_key" UNIQUE ("code")
);

CREATE TABLE "nullable_unique_refs" (
  "id" integer NOT NULL,
  "code" varchar(20),
  CONSTRAINT "nullable_unique_refs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "oversized_types" (
  "id" integer NOT NULL,
  "pg_varchar" text NOT NULL,
  "mysql_char" char(256) NOT NULL,
  "mysql_varchar" varchar(16384) NOT NULL,
  "sqlserver_char" char(4001) NOT NULL,
  "sqlserver_varchar" varchar(4001) NOT NULL,
  "pg_decimal" numeric(1000, 2) NOT NULL,
  "mysql_decimal" numeric(40, 31) NOT NULL,
  CONSTRAINT "oversized_types_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "oversized_unique" (
  "id" integer NOT NULL,
  "code" varchar(20000) NOT NULL,
  CONSTRAINT "oversized_unique_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "oversized_unique_code_key" UNIQUE ("code")
);

CREATE TABLE "required_a" (
  "id" integer NOT NULL,
  "b_id" integer NOT NULL,
  CONSTRAINT "required_a_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "required_b" (
  "id" integer NOT NULL,
  "a_id" integer NOT NULL,
  CONSTRAINT "required_b_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "required_child" (
  "id" integer NOT NULL,
  "a_id" integer NOT NULL,
  CONSTRAINT "required_child_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "right" (
  "id" integer NOT NULL,
  "root_id" integer NOT NULL,
  CONSTRAINT "right_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "root" (
  "id" integer NOT NULL,
  "leaf_id" integer,
  CONSTRAINT "root_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "text_keys" (
  "code" text NOT NULL,
  "label" text NOT NULL,
  "tag" text NOT NULL,
  CONSTRAINT "text_keys_pkey" PRIMARY KEY ("code"),
  CONSTRAINT "text_keys_label_key" UNIQUE ("label")
);

CREATE TABLE "text_refs" (
  "id" integer NOT NULL,
  "text_key_code" text NOT NULL,
  CONSTRAINT "text_refs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "tree_nodes" (
  "id" integer NOT NULL,
  "parent_id" integer,
  CONSTRAINT "tree_nodes_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "unique_only" (
  "code" varchar(20) NOT NULL,
  "label" text NOT NULL,
  CONSTRAINT "unique_only_code_key" UNIQUE ("code")
);

CREATE TABLE "wide_rows" (
  "id" integer NOT NULL,
  "v" varchar(16383) NOT NULL,
  CONSTRAINT "wide_rows_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "binary_keys_hash_ux" ON "binary_keys" ("hash");
CREATE UNIQUE INDEX "five_part_keys_ux" ON "five_part_keys" ("q1", "q2", "q3", "q4", "q5");
CREATE UNIQUE INDEX "four_part_keys_ux" ON "four_part_keys" ("p1", "p2", "p3", "p4");
CREATE UNIQUE INDEX "nullable_unique_alt_code_ux" ON "nullable_unique" ("alt_code");
CREATE INDEX "text_keys_tag_ix" ON "text_keys" ("tag");

ALTER TABLE "cycle_a" ADD CONSTRAINT "cycle_a_b_id_fkey" FOREIGN KEY ("b_id") REFERENCES "cycle_b" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "cycle_b" ADD CONSTRAINT "cycle_b_a_id_fkey" FOREIGN KEY ("a_id") REFERENCES "cycle_a" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "default_children" ADD CONSTRAINT "default_children_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "default_parents" ("id") ON DELETE SET DEFAULT ON UPDATE NO ACTION;
ALTER TABLE "five_part_refs" ADD CONSTRAINT "five_part_refs_q1_q2_q3_q4_q5_fkey" FOREIGN KEY ("q1", "q2", "q3", "q4", "q5") REFERENCES "five_part_keys" ("q1", "q2", "q3", "q4", "q5") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "fixed_refs" ADD CONSTRAINT "fixed_refs_fixed_code_fkey" FOREIGN KEY ("fixed_code") REFERENCES "fixed_keys" ("code") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "json_refs" ADD CONSTRAINT "json_refs_doc_fkey" FOREIGN KEY ("doc") REFERENCES "json_unique" ("doc") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "leaf" ADD CONSTRAINT "leaf_left_id_fkey" FOREIGN KEY ("left_id") REFERENCES "left" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "leaf" ADD CONSTRAINT "leaf_right_id_fkey" FOREIGN KEY ("right_id") REFERENCES "right" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "left" ADD CONSTRAINT "left_root_id_fkey" FOREIGN KEY ("root_id") REFERENCES "root" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "nullable_unique_refs" ADD CONSTRAINT "nullable_unique_refs_code_fkey" FOREIGN KEY ("code") REFERENCES "nullable_unique" ("code") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "required_a" ADD CONSTRAINT "required_a_b_id_fkey" FOREIGN KEY ("b_id") REFERENCES "required_b" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "required_b" ADD CONSTRAINT "required_b_a_id_fkey" FOREIGN KEY ("a_id") REFERENCES "required_a" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "required_child" ADD CONSTRAINT "required_child_a_id_fkey" FOREIGN KEY ("a_id") REFERENCES "required_a" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "right" ADD CONSTRAINT "right_root_id_fkey" FOREIGN KEY ("root_id") REFERENCES "root" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "root" ADD CONSTRAINT "root_leaf_id_fkey" FOREIGN KEY ("leaf_id") REFERENCES "leaf" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE "text_refs" ADD CONSTRAINT "text_refs_text_key_code_fkey" FOREIGN KEY ("text_key_code") REFERENCES "text_keys" ("code") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "tree_nodes" ADD CONSTRAINT "tree_nodes_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "tree_nodes" ("id") ON DELETE SET NULL ON UPDATE NO ACTION;

COMMENT ON TABLE "long_comments" IS 'ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt';
COMMENT ON COLUMN "long_comments"."note" IS 'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc';
COMMENT ON COLUMN "long_comments"."surrogate_note" IS 'sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss😀';
