import { describe, expect, it } from "vitest";

import type { Column } from "../../model/column.js";
import { createEmptySchema } from "../../model/create-empty-schema.js";
import type { ColumnId, TableId } from "../../model/ids.js";
import type { SchemaDocument } from "../../model/schema-document.js";
import {
  buildSchema,
  makeColumn,
  makeEnum,
  makeIndex,
  makeRelation,
  makeTable,
} from "../../testing/factories.js";
import { formatDiagnosticsSnapshot } from "../../testing/generator-snapshot.js";
import { createNamingEdgeSchema } from "../../testing/naming-edge-schema.js";
import { createSampleSchema } from "../../testing/sample-schema.js";
import { createTargetLimitSchema } from "../../testing/target-limit-schema.js";
import { buildSqlDdlModel } from "../shared/sql-ddl-model.js";
import { generatePostgresql } from "./generate-postgresql.js";

function column(
  id: ColumnId,
  tableId: TableId,
  overrides: Partial<Column> = {},
): Column {
  return makeColumn({ id, tableId, ...overrides });
}

function generate(schema: SchemaDocument): string {
  return generatePostgresql(schema, {}).file.content;
}

function reverseKeyOrder<Element>(
  map: Readonly<Record<string, Element>>,
): Record<string, Element> {
  return Object.fromEntries(Object.entries(map).reverse());
}

// Users and posts with a user index and a posts.author_id → users.id relation.
function createBlogSchema(
  actions: Pick<Parameters<typeof makeRelation>[0], "onDelete" | "onUpdate">,
): SchemaDocument {
  return buildSchema({
    tables: [
      makeTable({ id: "tbl_posts", name: "posts" }),
      makeTable({
        id: "tbl_users",
        name: "users",
        primaryKeyColumnIds: ["col_user_id"],
      }),
    ],
    columns: [
      column("col_post_author", "tbl_posts", { name: "author_id" }),
      column("col_user_id", "tbl_users", { name: "id" }),
    ],
    indexes: [
      makeIndex({
        id: "idx_author",
        tableId: "tbl_posts",
        name: "posts_author_idx",
        columnIds: ["col_post_author"],
      }),
    ],
    relations: [
      makeRelation({
        id: "rel_author",
        fromTableId: "tbl_posts",
        toTableId: "tbl_users",
        columnPairs: [
          { fromColumnId: "col_post_author", toColumnId: "col_user_id" },
        ],
        ...actions,
      }),
    ],
  });
}

describe("generatePostgresql", () => {
  it("names the file schema.sql with language sql", () => {
    const { file } = generatePostgresql(createEmptySchema("Empty"), {});

    expect({ fileName: file.fileName, language: file.language }).toStrictEqual({
      fileName: "schema.sql",
      language: "sql",
    });
  });

  it("creates enum types before tables", () => {
    const schema = buildSchema({
      enums: [
        makeEnum({
          id: "enum_status",
          name: "order_status",
          values: ["pending", "it's paid"],
        }),
      ],
      tables: [makeTable({ id: "tbl_orders", name: "orders" })],
      columns: [
        column("col_status", "tbl_orders", {
          name: "status",
          type: { kind: "enum", enumId: "enum_status" },
        }),
      ],
    });

    expect(generate(schema)).toBe(
      [
        "CREATE TYPE \"order_status\" AS ENUM ('pending', 'it''s paid');",
        "",
        'CREATE TABLE "orders" (',
        '  "status" "order_status" NOT NULL',
        ");",
        "",
      ].join("\n"),
    );
  });

  it("writes identity, not null and default in column order", () => {
    const schema = buildSchema({
      tables: [makeTable({ id: "tbl_users", name: "users" })],
      columns: [
        column("col_id", "tbl_users", {
          name: "id",
          type: { kind: "bigint" },
          isAutoIncrement: true,
        }),
        column("col_manager", "tbl_users", {
          name: "manager_id",
          type: { kind: "bigint" },
          isNullable: true,
        }),
        column("col_created", "tbl_users", {
          name: "created_at",
          type: { kind: "timestamptz" },
          defaultValue: { kind: "currentTimestamp" },
        }),
      ],
    });

    expect(generate(schema)).toBe(
      [
        'CREATE TABLE "users" (',
        '  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,',
        '  "manager_id" bigint,',
        '  "created_at" timestamptz NOT NULL DEFAULT now()',
        ");",
        "",
      ].join("\n"),
    );
  });

  it("writes the primary key and unique constraints after the columns", () => {
    const schema = buildSchema({
      tables: [
        makeTable({
          id: "tbl_users",
          name: "users",
          primaryKeyColumnIds: ["col_id"],
        }),
      ],
      columns: [
        column("col_id", "tbl_users", { name: "id" }),
        column("col_email", "tbl_users", {
          name: "email",
          type: { kind: "varchar", length: 255 },
          isUnique: true,
        }),
      ],
    });

    expect(generate(schema)).toBe(
      [
        'CREATE TABLE "users" (',
        '  "id" integer NOT NULL,',
        '  "email" varchar(255) NOT NULL,',
        '  CONSTRAINT "users_pkey" PRIMARY KEY ("id"),',
        '  CONSTRAINT "users_email_key" UNIQUE ("email")',
        ");",
        "",
      ].join("\n"),
    );
  });

  it("writes a table without columns as an empty column list", () => {
    const schema = buildSchema({
      tables: [makeTable({ id: "tbl_t", name: "t" })],
    });

    expect(generate(schema)).toBe('CREATE TABLE "t" ();\n');
  });

  it("creates indexes before foreign keys", () => {
    const content = generate(createBlogSchema({}));

    expect(content).toContain(
      [
        'CREATE INDEX "posts_author_idx" ON "posts" ("author_id");',
        "",
        'ALTER TABLE "posts" ADD CONSTRAINT "posts_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;',
      ].join("\n"),
    );
  });

  it("writes a unique index with the UNIQUE keyword and every column", () => {
    const schema = buildSchema({
      tables: [makeTable({ id: "tbl_t", name: "t" })],
      columns: [
        column("col_a", "tbl_t", { name: "a" }),
        column("col_b", "tbl_t", { name: "b" }),
      ],
      indexes: [
        makeIndex({
          id: "idx_ab",
          tableId: "tbl_t",
          name: "t_a_b_key",
          columnIds: ["col_a", "col_b"],
          isUnique: true,
        }),
      ],
    });

    expect(generate(schema)).toContain(
      'CREATE UNIQUE INDEX "t_a_b_key" ON "t" ("a", "b");',
    );
  });

  it("adds foreign keys with both actions after every table", () => {
    const content = generate(
      createBlogSchema({ onDelete: "cascade", onUpdate: "setNull" }),
    );

    expect(content.indexOf("ALTER TABLE")).toBeGreaterThan(
      content.lastIndexOf("CREATE TABLE"),
    );
    expect(content).toContain("ON DELETE CASCADE ON UPDATE SET NULL;");
  });

  it("writes restrict as RESTRICT and set default as SET DEFAULT", () => {
    const content = generate(
      createBlogSchema({ onDelete: "restrict", onUpdate: "setDefault" }),
    );

    expect(content).toContain("ON DELETE RESTRICT ON UPDATE SET DEFAULT;");
  });

  it("writes table comments before their column comments at the end", () => {
    const schema = buildSchema({
      tables: [
        makeTable({ id: "tbl_a", name: "a", comment: "Bảng a" }),
        makeTable({ id: "tbl_b", name: "b", comment: "Bảng b" }),
      ],
      columns: [
        column("col_a1", "tbl_a", { name: "x", comment: "Cột x" }),
        column("col_a2", "tbl_a", { name: "y" }),
        column("col_a3", "tbl_a", { name: "z", comment: "Cột z" }),
        column("col_b1", "tbl_b", { name: "w", comment: "Cột w" }),
      ],
    });

    expect(generate(schema).split("\n\n").at(-1)).toBe(
      [
        "COMMENT ON TABLE \"a\" IS 'Bảng a';",
        'COMMENT ON COLUMN "a"."x" IS \'Cột x\';',
        'COMMENT ON COLUMN "a"."z" IS \'Cột z\';',
        "COMMENT ON TABLE \"b\" IS 'Bảng b';",
        'COMMENT ON COLUMN "b"."w" IS \'Cột w\';',
        "",
      ].join("\n"),
    );
  });

  it("quotes a table name containing a double quote", () => {
    const schema = buildSchema({
      tables: [makeTable({ id: "tbl_t", name: 'my "table"' })],
    });

    expect(generate(schema)).toBe('CREATE TABLE "my ""table""" ();\n');
  });

  it("escapes a comment containing quotes and a comment terminator", () => {
    const schema = buildSchema({
      tables: [
        makeTable({ id: "tbl_t", name: "t", comment: 'it\'s */ -- "done"' }),
      ],
    });

    expect(generate(schema)).toContain(
      "COMMENT ON TABLE \"t\" IS 'it''s */ -- \"done\"';",
    );
  });

  it("keeps constraints with json and binary columns", () => {
    const schema = buildSchema({
      tables: [
        makeTable({ id: "tbl_t", name: "t", primaryKeyColumnIds: ["col_doc"] }),
      ],
      columns: [
        column("col_doc", "tbl_t", { name: "doc", type: { kind: "json" } }),
        column("col_hash", "tbl_t", {
          name: "hash",
          type: { kind: "binary" },
          isUnique: true,
        }),
      ],
    });

    expect(generate(schema)).toContain(
      [
        '  CONSTRAINT "t_pkey" PRIMARY KEY ("doc"),',
        '  CONSTRAINT "t_hash_key" UNIQUE ("hash")',
      ].join("\n"),
    );
  });

  it("returns the diagnostics of the ddl model", () => {
    const schema = createTargetLimitSchema();

    expect(generatePostgresql(schema, {}).diagnostics).toStrictEqual(
      buildSqlDdlModel(schema, "postgresql").diagnostics,
    );
  });

  it("writes an empty schema as a single newline", () => {
    expect(generate(createEmptySchema("Empty"))).toBe("\n");
  });

  it("contains no DROP, BEGIN or COMMIT for the sample schema", () => {
    expect(generate(createSampleSchema())).not.toMatch(
      /\b(?:DROP|BEGIN|COMMIT)\b/,
    );
  });

  it("returns the same content when map keys were inserted in a different order", () => {
    const schema = createSampleSchema();
    const reordered: SchemaDocument = {
      ...schema,
      tables: reverseKeyOrder(schema.tables),
      columns: reverseKeyOrder(schema.columns),
      relations: reverseKeyOrder(schema.relations),
      indexes: reverseKeyOrder(schema.indexes),
      enums: reverseKeyOrder(schema.enums),
    };

    expect(generatePostgresql(reordered, {})).toStrictEqual(
      generatePostgresql(schema, {}),
    );
  });

  it.each<[string, () => SchemaDocument]>([
    ["sample", createSampleSchema],
    ["naming-edge", createNamingEdgeSchema],
    ["target-limit", createTargetLimitSchema],
    ["empty", () => createEmptySchema("Empty")],
  ])("matches the snapshot for %s", async (fixture, createSchema) => {
    const result = generatePostgresql(createSchema(), {});

    await expect(result.file.content).toMatchFileSnapshot(
      `../__snapshots__/postgresql/${fixture}.sql`,
    );
    await expect(
      formatDiagnosticsSnapshot(result.diagnostics),
    ).toMatchFileSnapshot(
      `../__snapshots__/postgresql/${fixture}.diagnostics.txt`,
    );
  });
});
