import type { SchemaDocument } from "../../model/schema-document.js";
import type {
  Generate,
  GenerateResult,
  GeneratorOptions,
} from "../shared/generator-types.js";
import { quoteSqlIdentifier } from "../shared/identifiers.js";
import { renderFileContent } from "../shared/render-file.js";
import type {
  SqlColumnModel,
  SqlEnumModel,
  SqlForeignKeyModel,
  SqlIndexModel,
  SqlTableModel,
  SqlUniqueModel,
} from "../shared/sql-ddl-model.js";
import { buildSqlDdlModel } from "../shared/sql-ddl-model.js";
import { sqlStringLiteral } from "../shared/sql-literals.js";
import { REFERENTIAL_ACTION_SQL } from "../shared/sql-referential-actions.js";
import { renderPostgresqlType } from "./render-postgresql-type.js";

export type PostgresqlOptions = GeneratorOptions["postgresql"];

const COLUMN_INDENT = "  ";

function quote(name: string): string {
  return quoteSqlIdentifier("postgresql", name);
}

function literal(value: string): string {
  return sqlStringLiteral("postgresql", value);
}

function quoteList(names: readonly string[]): string {
  return names.map(quote).join(", ");
}

function renderEnum(element: SqlEnumModel): string {
  const values = element.values.map(literal).join(", ");
  return `CREATE TYPE ${quote(element.name)} AS ENUM (${values});`;
}

function renderColumn(
  column: SqlColumnModel,
  enums: SchemaDocument["enums"],
): string {
  return [
    `${COLUMN_INDENT}${quote(column.name)} ${renderPostgresqlType(column.type, enums)}`,
    column.isAutoIncrement ? " GENERATED BY DEFAULT AS IDENTITY" : "",
    column.isNullable ? "" : " NOT NULL",
    column.defaultSql === null ? "" : ` DEFAULT ${column.defaultSql}`,
  ].join("");
}

function renderConstraint(constraint: SqlUniqueModel, kind: string): string {
  return `${COLUMN_INDENT}CONSTRAINT ${quote(constraint.name)} ${kind} (${quoteList(constraint.columnNames)})`;
}

function renderTable(
  table: SqlTableModel,
  enums: SchemaDocument["enums"],
): readonly string[] {
  const elements = [
    ...table.columns.map((column) => renderColumn(column, enums)),
    ...(table.primaryKey === null
      ? []
      : [renderConstraint(table.primaryKey, "PRIMARY KEY")]),
    ...table.uniqueConstraints.map((unique) =>
      renderConstraint(unique, "UNIQUE"),
    ),
  ];
  const header = `CREATE TABLE ${quote(table.name)} (`;
  if (elements.length === 0) {
    return [`${header});`];
  }
  return [header, elements.join(",\n"), ");"];
}

function renderIndex(index: SqlIndexModel): string {
  const unique = index.isUnique ? "UNIQUE " : "";
  return `CREATE ${unique}INDEX ${quote(index.name)} ON ${quote(index.tableName)} (${quoteList(index.columnNames)});`;
}

function renderForeignKey(foreignKey: SqlForeignKeyModel): string {
  return [
    `ALTER TABLE ${quote(foreignKey.tableName)}`,
    `ADD CONSTRAINT ${quote(foreignKey.name)}`,
    `FOREIGN KEY (${quoteList(foreignKey.columnNames)})`,
    `REFERENCES ${quote(foreignKey.referencedTableName)} (${quoteList(foreignKey.referencedColumnNames)})`,
    `ON DELETE ${REFERENTIAL_ACTION_SQL[foreignKey.onDelete]}`,
    `ON UPDATE ${REFERENTIAL_ACTION_SQL[foreignKey.onUpdate]};`,
  ].join(" ");
}

function renderComments(table: SqlTableModel): readonly string[] {
  const tableName = quote(table.name);
  return [
    ...(table.comment === ""
      ? []
      : [`COMMENT ON TABLE ${tableName} IS ${literal(table.comment)};`]),
    ...table.columns
      .filter((column) => column.comment !== "")
      .map(
        (column) =>
          `COMMENT ON COLUMN ${tableName}.${quote(column.name)} IS ${literal(column.comment)};`,
      ),
  ];
}

// CG-01 has no options, so the implementation leaves out the second parameter
// of `Generate` instead of declaring an unused one.
export const generatePostgresql: Generate<"postgresql"> = (
  schema: SchemaDocument,
): GenerateResult => {
  const model = buildSqlDdlModel(schema, "postgresql");
  const content = renderFileContent([
    model.enums.map(renderEnum),
    ...model.tables.map((table) => renderTable(table, schema.enums)),
    model.indexes.map(renderIndex),
    model.foreignKeys.map(renderForeignKey),
    model.tables.flatMap(renderComments),
  ]);
  return {
    file: { fileName: "schema.sql", language: "sql", content },
    diagnostics: model.diagnostics,
  };
};
